# Generated by Django 5.0.6 on 2024-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
