# Generated by Django 5.2.9 on 2025-12-28 14:30

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0002_alter_company_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='designer/')),
            ],
            options={
                'db_table': 'Designer',
            },
            bases=('UserManagment.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
