# Generated by Django 5.2.9 on 2025-12-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0003_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='static/agent/'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='static/designer/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ProfilePicture',
            field=models.ImageField(blank=True, upload_to='static/uploads/profile'),
        ),
    ]
