# Generated by Django 5.2.9 on 2025-12-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='product',
            new_name='Product',
        ),
    ]
