# Generated by Django 5.2.9 on 2025-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_product_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='static/product/'),
        ),
    ]
