# Generated by Django 5.2.9 on 2025-12-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='file',
            field=models.FileField(upload_to='static/design/'),
        ),
    ]
