# Generated by Django 5.2.9 on 2026-01-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_design_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
